### ISSUE TITLE
Bot links to wrong faction pages.

### ISSUE THREAD

**Issue by HobbitCraft** [ronoaldo/ap-5r#31]
When trying to find First Order characters from a swgoh.gg page, the command "/faction First Order" is used. Unfortunately this links to a page ending with First-Order not First+Order which is how swgoh.gg filters factions.

**Comment by ronoaldo** [comment]
I think it is now fixed!

![image](https://user-images.githubusercontent.com/564649/48926624-e9df8a80-eeb6-11e8-9bd1-d09e761c18a6.png)

**Comment by ronoaldo** [comment]
@HobbitCraft kindly confirm if it is fixed for you, otherwise reopen here. Thank you!

**Comment by HobbitCraft** [comment]
Fixed! Thanks 
![image](https://user-images.githubusercontent.com/3309569/48957201-18a93f80-ef4f-11e8-83e6-a0d5402861c7.png)
